Run cssesc through babel-loader
We were getting this error from Uglify during webpack build:

  ERROR in HappoApp.bundle.js from UglifyJs
  SyntaxError: Unexpected token name «key», expected punc «;» [./~/cssesc/cssesc.js:11,0]

Turns out cssesc doesn't provide any browser-ready bundle. So we have to
run it through babel ourselves.